###############################################################################
#                                                                             #
#   This file is a Makefile with rules for the MBR parsing code.              #
#                                                                             #
#   Author: Wolfgang Richter <wolf@cs.cmu.edu>                                #
#   License: MIT                                                              #
#                                                                             #
###############################################################################

test:
	@./process_mbr.py test.raw
